version: '2'
services:
    prop_mgmnt-app:
        image: prop_mgmnt
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://prop_mgmnt-mysql:3306/prop_mgmnt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prop_mgmnt-mysql:
        extends:
            file: mysql.yml
            service: prop_mgmnt-mysql
